# Generated by Django 5.0.3 on 2024-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=255)),
                ('travel_city', models.CharField(max_length=255)),
                ('depart_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('passengers', models.IntegerField()),
                ('travel_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='123-456-7890', max_length=14),
        ),
    ]
